select* from apple;

# checking for null values
select `date` from apple
where `Date`is null;
select  Platform from apple
where Platform is null;
select  Product_Category from apple
where Product_Category is null;
select  Model_Name from apple
where Model_Name is null;
select  `Condition` from apple
where `Condition` is null;
select  Launch_Price_USD from apple
where Launch_Price_USD is null;
select  Launch_Price_INR from apple
where Launch_Price_INR is null;
select  Current_Price_USD from apple
where Current_Price_USD is null;
select  Current_Price_INR from apple
where Current_Price_INR is null;
select  Discount_Pct from apple
where Discount_Pct is null;
select  Sale_Event from apple
where Sale_Event is null;
select  Stock_Status from apple
where Stock_Status is null;
select  Rating from apple
where Rating is null;
select  Reviews_Count from apple
where Reviews_Count is  null;


#total  revenue  per model

select  distinct Model_Name,
Launch_Price_USD*count(Model_Name)  as revenue_USD,
Launch_Price_INR*count(Model_Name)  as revenue_INR
from apple
group by Model_Name,Launch_Price_USD,Launch_Price_INR
order by Model_Name;

#total revenue per year

select 
distinct `year`,
sum(`count`)*sum(Launch_Price_USD) as revenue_USD,
sum(`count`)*sum(Launch_Price_INR)as revenue_INR 
from
 (select  year(date) as `year`,
 count(Product_Category) as `count`,
 Launch_Price_USD,
 Launch_Price_INR
 from apple
 group by Launch_Price_USD, Launch_Price_INR,
`year`) as t
group by `year`;

#revenue generated by events 

select distinct Sale_Event ,
count(Sale_Event)*sum(Launch_Price_USD) as revenue_USD,
count(Sale_Event)*sum(Launch_Price_INR) as revenue_INR 
from apple
group by Sale_Event;


#  year and month wise selling of products

select  rank() over(partition by Product_Category,year(date) order by  count(Product_Category) ) as `no.`,
Product_Category,
 year(date) as `year`,monthname(date) as `month`,
 count(Product_Category) as `count` 
from apple
group by Product_Category,`year`,`month`
order by `year`;

#Average discount and frequency of discounting, by platform

select platform,
round(avg(discount_pct),2) as discount,
count(*) as product_
from apple
group by platform;

#frequency of platform  provided discounts

#amazon

select 
 product_category,
 round(avg(discount_pct),2) as amazon
from apple
where platform="amazon"
group by Product_Category,platform;

#flipkart

select 
 product_category,
 round(avg(discount_pct),2) as flipkart
from apple
where platform="flipkart"
group by Product_Category,platform;

#together with count

select platform,
 product_category,
 count(Product_Category),
case when  platform = "amazon" then round(avg(Discount_Pct),2) else round(avg(Discount_Pct),2)end  as discount
from apple
group by Product_Category,platform
order by Product_Category;

#Is the refurbished discount high enough to cannibalize new product sales--

SELECT `condition`, round(avg(Discount_Pct),2) as discount
from apple
where discount_pct>0
group by `condition`;

# price trends over time from launch (Launch_Price_USD/INR) to current listing price (Current_Price_USD/INR)

select 
 row_number () over(partition by (product_category)order by launched_year) as no_of_product,
product_category,
launched_year,
 round( 100*((Launch_Price_USD -Current_Price_USD) /Launch_Price_USD),1) as  price_drop_by_percentage_USD,
round( 100*((Launch_Price_INR-Current_Price_INR) /Launch_Price_INR),1) as price_drop_by_percentage_INR
from
(select year(date) as launched_year, product_category,
avg(Launch_Price_USD) as Launch_Price_USD,
avg(Current_Price_USD) as Current_Price_USD,
avg(Launch_Price_INR) as Launch_Price_INR,
avg(Current_Price_INR) as Current_Price_INR
from apple
group by year(date),Product_Category) as t
order by product_category;

#stock status of product category

select distinct
rank()over(partition by model_name order by stock_status) as `rank`,
 Model_Name,Stock_Status,count(Stock_Status) as `count` from apple
group by Model_Name,Stock_Status
order by model_name;
